modloader="javafml"
loaderVersion="[31,)"
credits="thanks to the MMD Discord for helping me with problems, also thanks suppergerrie2 for their tutorials"
[[mods]]
modId="testmod"
version="1.0"
displayName="Test Mod"
description='''
OH GOD
HE'S BACK
WHY
END ME
STOP THE PAIN
'''